run-name: Build push and deploy (CD)
on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref_type == 'branch' && github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read
    outputs:
      image-name: ${{ steps.set-image-name.outputs.image_name }}
      release-version: ${{ steps.set-image-name.outputs.release_version }}
    steps:
      - uses: actions/checkout@v4
      - uses: 'google-github-actions/auth@v2'
        with:
           credentials_json: '${{ secrets.GCLOUD_SERVICE_ACCOUNT_SECRET_JSON }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          install_components: beta
      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet
      - name: Set controller release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.14.0
          cache: npm

      - name: npm install
        run: npm ci
      - name: build application
        run: npm run build
      - name: npm install fe
        run: npm ci
        working-directory: fe
      - name: build fe
        run: npm run build
        working-directory: fe
      - name: Set package version
        run: npm version --no-git-tag-version ${{ env.RELEASE_VERSION }}
        if: github.ref_type == 'tag'
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            asia-southeast1-docker.pkg.dev/elastic-ml/jina-demo/wikipedia-vector-demo
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        id: container
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Set image name
        id: set-image-name
        run: |
          echo "image_name=asia-southeast1-docker.pkg.dev/elastic-ml/jina-demo/wikipedia-vector-demo@${{steps.container.outputs.imageid}}" >> $GITHUB_OUTPUT
          echo "release_version=${{ env.RELEASE_VERSION }}" >> $GITHUB_OUTPUT

  deploy-services:
    runs-on: ubuntu-latest
    needs: build-and-push-to-gcr
    if: github.ref_name != 'ops'
    strategy:
      matrix:
        region: [asia-southeast1]
    steps:
      - uses: 'google-github-actions/auth@v2'
        with:
           credentials_json: '${{ secrets.GCLOUD_SERVICE_ACCOUNT_SECRET_JSON }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          install_components: beta
      - name: Deploy Demo Server with Tag (${{ matrix.region }})
        run: |
          gcloud beta run deploy wikipedia-vector-demo --image ${{ needs.build-and-push-to-gcr.outputs.image-name }} --tag ${{ needs.build-and-push-to-gcr.outputs.release-version }} --command '' --args build/server.js --region ${{ matrix.region }} --async --min-instances 0 --deploy-health-check --use-http2
